git: true
subtree_only: true
yes_always: true
map_tokens: 2048
models:
  - gpt-4o-mini      # или другой доступный
files:
  - .github/workflows/ci.yml
  - apps/web/**
  - package.json
  - pnpm-workspace.yaml
read_only:
  - apps/web/pnpm-lock.yaml
