name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Fake URL so anything that inspects env won't fail (we DO NOT run migrations in CI)
      DATABASE_URL: "postgresql://user:pass@localhost:5432/postgres"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # DO NOT use 'cache: pnpm' here because there is no pnpm-lock.yaml in the repo root

      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile

      - name: Show versions (debug)
        run: |
          node -v
          pnpm -v

      - name: Typecheck
        run: pnpm typecheck

      - name: Build web
        run: pnpm --filter @foodtech/web build
