name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web:
    runs-on: ubuntu-latest

    # Все команды по-умолчанию выполняем в папке web-приложения
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          # если добавите lock-файл, лучше укажите на него путь (иначе можно оставить так)
          cache-dependency-path: apps/web/pnpm-lock.yaml

      # ВАЖНО: ставим pnpm через официальный экшен, НО БЕЗ указания version —
      # тогда экшен возьмёт версию из package.json (ключ "packageManager")
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        # пока можно без lock-файла; когда появится pnpm-lock.yaml — добавим --frozen-lockfile
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build

