name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        run: npm install -g pnpm@8
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build project (if build script exists)
        run: pnpm build
        continue-on-error: true
      
      - name: Run tests (if test script exists)
        run: pnpm test
        continue-on-error: true
      
      - name: Run linting (if lint script exists)
        run: pnpm lint
        continue-on-error: true
