name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Берём PNPM из package.json -> packageManager (без указания version!)
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      # Node 20. Кэш PNPM включай только если lockfile закоммичен (см. блок B)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: pnpm
          # cache-dependency-path: pnpm-lock.yaml

      - name: Show versions
        run: |
          node -v
          pnpm -v

      - name: Install deps
        run: pnpm install

      - name: Typecheck
        run: pnpm -F @foodtech/web typecheck

      - name: Build web
        run: pnpm -F @foodtech/web build
